version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12222222q
      POSTGRES_DB: youtube_clone
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Монтуємо локальний дамп в папку автозапуску контейнера
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      # Важливо: хост бази даних тепер не 127.0.0.1, а назва сервісу БД - 'db'
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=youtube_clone
      - DB_USER=postgres
      - DB_PASS=12222222q
      - JWT_SECRET=super_secret_key_for_youtube_clone_change_in_production
    volumes:
      # Синхронізація локальних файлів з контейнером (Hot reload)
      - ./backend:/var/www/html
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules # Запобігає перезапису node_modules з хоста
    depends_on:
      - backend

volumes:
  pgdata: # Зберігає дані БД між перезапусками контейнерів